p_test/api/urls.py
from django.urls import path

from p_test.api.api import (
    person_api_view, person_detail_view, HobbiesListAPIView, PersonListCreateAPIView,
    PersonRetrieveUpdateDestroyAPIView
)


urlpatterns = [
    path('persons/', person_api_view, name='person_api_view'),
    path('persons/<int:pk>/', person_detail_view, name='person_detail_api_view'),
    path('hobbies/', HobbiesListAPIView.as_view(), name='hobbies_api_view'),
    path('persons/list-create/', PersonListCreateAPIView.as_view(), name='person_list_create'),
    path('persons/retrieve-update-delete/<int:pk>/', PersonRetrieveUpdateDestroyAPIView.as_view(),
         name='person_retrieve_update_delete'),
]

p_test/urls.py
from django.urls import path

from p_test.views import (
    PersonCreateView, update_person, create_person, PersonListView, PersonDetailView, import_person_view
)


app_name = 'p_test'
urlpatterns = [
    path('person/list', PersonListView.as_view(), name='list'),
    path('person/detail/<int:pk>/', PersonDetailView.as_view(), name='detail'),
    path('person/<int:id>/<str:name>/update', update_person, name='update'),
    path('person/new', create_person, name='create'),
    path('person/import', import_person_view, name='import_person_view'),
]

project_test/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('p_test.urls')),
    path('persons/', include('p_test.api.routers')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

p_test/models.py
from django.db import models


class Person(models.Model):
    name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250, blank=True, null=True)
    email = models.CharField(max_length=250, blank=True, null=True)
    cell_phone = models.CharField(max_length=250, blank=True, null=True)
    photo = models.ImageField(upload_to='p_test/photos', blank=True, null=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return '{0} {1}'.format(self.name, self.last_name)

    def list_hobbies(self):
        hobbies = list(self.hobbies_set.all().values_list('name', flat=True))
        return ', '.join(hobbies)


class Profile(models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    address = models.CharField(max_length=250, null=True, blank=True)
    job = models.CharField(max_length=250, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Profile: {0}'.format(self.person.name)


class Hobbies(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    name = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return "{0}' hobby: {1}".format(self.person.name, self.name)

p_test/forms.py
from django import forms


from p_test.models import Person


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('name', 'last_name', 'email', 'photo')

p_test/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from data_importer.forms import FileUploadHistoryForm
from p_test.importers import PersonImporter
from p_test.models import Person

from p_test.forms import PersonForm
from students.models import Careers, Students


# Create your views here.
from students.forms import StudentsForm


def list_persons(request):
    persons = Person.objects.all().values('id', 'name')

    context = {
        'persons': persons
    }
    return render(request, 'p_test/list.html', context)


class PersonListView(ListView):
    template_name = 'p_test/list.html'
    model = Person
    context_object_name = 'persons'

    def get_queryset(self):
        persons = Person.objects.all()
        return persons


def detail_person(request, id):
    try:
        person = Person.objects.get(id=id)
        exists = True
    except Person.DoesNotExist:
        person = 'Does not exist.'
        exists = False

    context = {
        'person': person,
        'exists': exists
    }

    return render(request, 'p_test/detail.html', context)


class PersonDetailView(DetailView):
    template_name = 'p_test/detail.html'
    queryset = Person.objects.all()


def update_person(request, id, name):
    try:
        person = Person.objects.get(id=id)
        person.name = name
        person.save()
        message = 'Updated.'
    except Person.DoesNotExist:
        message = 'Not Updated.'

    context = {
        'message': message
    }

    return render(request, 'p_test/update.html', context)


def create_person(request):
    title = 'Create Student'

    if request.method == 'POST':
        form = PersonForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = PersonForm()

    context = {
        'form': form,
        'title': title
    }

    return render(request, 'p_test/create.html', context)


class PersonCreateView(CreateView):
    template_name = 'p_test/create.html'
    form_class = PersonForm
    success_url = reverse_lazy('p_test:list')


def import_person_view(request):
    template_name = 'data_importer/template_importer.html'
    context = {
        'title': 'Person Importer',
        'form': FileUploadHistoryForm()
    }

    if request.method == 'POST':
        form = FileUploadHistoryForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.name = 'Person Importer'
            instance.user = request.user
            instance.save()

            importer = PersonImporter(instance=instance)
            importer.execute()

            context.update({
                'form': form,
                'message': 'File imported successfully.'
            })

        else:
            context.update({'form': form})

    return render(request, template_name, context)

p_test/templates/p_test/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>

p_test/templates/p_test/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>Name: {{ person.name }}</p>
    <p>Last Name: {{ person.last_name }}</p>
    <p>Email: {{ person.email }}</p>
    <p>Address: {{ person.address }}</p>
</body>
</html>

p_test/templates/p_test/list.html
<!DOCTYPE html>
{% load static p_test_extras %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Testing Views</title>
    <link rel="stylesheet" href="{% static 'css/css_2/my_styles.css' %}">
</head>

<body>
<h1>Person List</h1>
<ul>
    {% for person in persons %}
        <li id="li-style">Name: <a href="{% url 'p_test:detail' person.id  %}">{{ person.name }}</a></li>
        <li>Hobbies: {{ person|hobby_list }}</li>
    {% endfor %}

{#    {% for person in object_list %}#}
{#        <li>Name: <a href="{% url 'p_test:detail' person.id  %}">{{ person.name }}</a></li>#}
{#    {% endfor %}#}


</ul>
</body>
    <script>

    </script>
</html>

p_test/templates/p_test/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ message }}
</body>
</html>